### ISSUE TITLE
Exploratory tesztelés

### ISSUE THREAD

**Issue by AngeliPeter** [BME-MIT-IET/roboam-iet-2020#7]
Én(@vkhobor) csinálok egy nodejs alapú exploratory tesztfájlt.
@AngeliPeter te meg egy html alapú megközelítést használj!

**Comment by vkhobor** [comment]
Én csinálok egy nodejs alapú exploratory tesztfájlt.
Peti te meg egy html alapú megközelítést használj.

**Comment by vkhobor** [comment]
d569c70b9c527c4e10c346ac8ad14d2a40a6f5e3

**Comment by AngeliPeter** [comment]
Óh kiválló ötlet 💯

**Comment by AngeliPeter** [comment]
d569c70b9c527c4e10c346ac8ad14d2a40a6f5e3 👍
